### ISSUE TITLE
what this library do

### ISSUE THREAD

**Issue by Mhde96** [mrousavy/react-native-google-nearby-messages#76]
i install this library with example 
and i don't know what can i do in this library 

please explain or give me link for more details 

Edit
i run this example on tow device and discovered 
but what i can do after that

**Comment by mrousavy** [comment]
![Screenshot 2020-10-30 at 08 58 50](https://user-images.githubusercontent.com/15199031/97674626-21d1ae00-1a8e-11eb-8b4a-4410b095814c.png)


As mentioned in the "About" page, you can publish strings and other users can see those strings when they are nearby. Using this you can build stuff like nearby secret chats, validation that users are nearby, crypto stuff, etc.

**Comment by Mhde96** [comment]
Thx Pro
can i get information like
 Device name - bluetooth mac address -

**Comment by mrousavy** [comment]
Yes, you can share that information by putting it in your message object. There's information on how to "send" data (= publishing) in the repo README.
