### ISSUE TITLE
[QUESTION] Why unpublish() is not declared as async in index.ts ?

### ISSUE THREAD

**Issue by SeanXu1984** [mrousavy/react-native-google-nearby-messages#98]
# Question
Hello Marc,

Why unpublish() is not declared as async in index.ts while in https://github.com/mrousavy/react-native-google-nearby-messages/blob/master/android/src/main/java/com/mrousavy/nearby/GoogleNearbyMessagesModule.kt#L191 it is declared as async?
I mean if I call publish() right after unpublish(), the unpublish might still be in progress, right?
Thanks

# Environment

```
paste the output of `react-native info` here
```

```json
"react": PASTE_VERSION_HERE,
"react-native": PASTE_VERSION_HERE,
"react-native-google-nearby-messages": PASTE_VERSION_HERE
```

**Comment by mrousavy** [comment]
You're right! Unpublish should be async too. Can you open a PR to fix this on the JS side?

**Comment by mrousavy** [comment]
nvm, fixed it

**Comment by SeanXu1984** [comment]
Thanks very much for your quick fix. 
Now I have noticed the ios side func unpublish() does not seem to be async so the interface change will not break the ios side unpublish() ?
